In [1]:
q1 = "I just discovered the course, can I still join?"
q2 = "I just found out about the program, can I still enroll?"

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [2]:
q1 = "Can I still join the course after the start date?"
v1 = model.encode(q1)

In [3]:
d  = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)

In [4]:
v1.dot(dv)

np.float32(0.32332397)

In [5]:
q2 = "How to install Docker on Windows?"
v2 = model.encode(q2)

In [6]:
v2.dot(dv)

np.float32(0.019730438)

In [7]:
q3 = "I have registered for the LLM Zoomcamp. When can I expect to receive the confirmation email?"
v3 = model.encode(q3)
v3.dot(dv)

np.float32(0.3271543)

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [2]:
from ingest import load_faq_data

documents = load_faq_data()

In [7]:
len(documents)

1

In [10]:
documents[0]

10

In [12]:
print(len(documents))

1


In [13]:
documents[0]

10

In [14]:
documents[0]["question"]

TypeError: 'int' object is not subscriptable

In [15]:
print(len(documents))

1


In [16]:
print(type(documents))
print(documents)

<class 'list'>
[10]


In [17]:
documents = load_faq_data()

In [18]:
documents = documents[:1]

In [19]:
print(documents)

[{'id': '9e508f2212', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: When does the course start?', 'answer': "A new cohort runs roughly January–April every year. For the current cohort's exact start date and registration link, check the [course repo README](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n\n- Register via the link in the course repo before the cohort starts.\n- Join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.\n- Join DataTalks.Club's [Slack](https://datatalks.club/docs/general/slack/) and the `#course-data-engineering` channel."}]


In [20]:
documents[0]["question"]

'Course: When does the course start?'

In [21]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

In [22]:
texts[0]

"Course: When does the course start? A new cohort runs roughly January–April every year. For the current cohort's exact start date and registration link, check the [course repo README](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n\n- Register via the link in the course repo before the cohort starts.\n- Join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.\n- Join DataTalks.Club's [Slack](https://datatalks.club/docs/general/slack/) and the `#course-data-engineering` channel."

In [28]:
len(texts)

1

In [26]:
from tqdm.auto import tqdm

In [27]:
batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/1 [00:00<?, ?it/s]

1

In [31]:
vectors[0]


array([-2.67062094e-02, -1.22457571e-01,  1.59441885e-02,  6.09419961e-03,
       -1.11915227e-02, -6.55021220e-02, -7.62883797e-02, -2.08820179e-02,
       -9.27567780e-02,  3.55664976e-02,  3.15623134e-02, -1.09016849e-02,
       -2.45336238e-02, -1.82476435e-02,  3.43917534e-02, -1.32052312e-02,
        7.22679263e-03, -1.54126719e-01,  6.41842633e-02, -9.07446630e-03,
        3.94655243e-02, -2.99637634e-02,  2.08512563e-02,  3.71391885e-02,
        3.52526903e-02, -2.49498920e-03,  7.71128982e-02,  2.78048143e-02,
        1.54832425e-02,  4.92820330e-03,  1.48515927e-03,  3.93927433e-02,
        7.25188702e-02,  9.02841315e-02,  5.25653213e-02,  2.72272285e-02,
        3.86085548e-02, -7.50262886e-02, -2.48754397e-02,  1.06018268e-01,
       -4.82871048e-02, -5.00598401e-02, -4.16486636e-02,  7.91618228e-02,
        5.06461784e-02, -3.68626090e-04, -2.83321901e-03, -2.59598326e-02,
       -3.82818393e-02,  8.59545767e-02, -2.85155028e-02, -7.23346621e-02,
       -2.05845628e-02,  

In [34]:
X

array([[-2.67062094e-02, -1.22457571e-01,  1.59441885e-02,
         6.09419961e-03, -1.11915227e-02, -6.55021220e-02,
        -7.62883797e-02, -2.08820179e-02, -9.27567780e-02,
         3.55664976e-02,  3.15623134e-02, -1.09016849e-02,
        -2.45336238e-02, -1.82476435e-02,  3.43917534e-02,
        -1.32052312e-02,  7.22679263e-03, -1.54126719e-01,
         6.41842633e-02, -9.07446630e-03,  3.94655243e-02,
        -2.99637634e-02,  2.08512563e-02,  3.71391885e-02,
         3.52526903e-02, -2.49498920e-03,  7.71128982e-02,
         2.78048143e-02,  1.54832425e-02,  4.92820330e-03,
         1.48515927e-03,  3.93927433e-02,  7.25188702e-02,
         9.02841315e-02,  5.25653213e-02,  2.72272285e-02,
         3.86085548e-02, -7.50262886e-02, -2.48754397e-02,
         1.06018268e-01, -4.82871048e-02, -5.00598401e-02,
        -4.16486636e-02,  7.91618228e-02,  5.06461784e-02,
        -3.68626090e-04, -2.83321901e-03, -2.59598326e-02,
        -3.82818393e-02,  8.59545767e-02, -2.85155028e-0

In [32]:
import numpy as np
X = np.array(vectors)

In [33]:
X.shape

(1, 384)

In [35]:
query = "Can I still join the course after the start date?"
v_query = model.encode(query)

In [36]:
scores = X.dot(v_query)

In [37]:
scores

array([0.4874058], dtype=float32)

In [38]:
scores = [v_query.dot(X[i]) for i in range(len(X))]

In [39]:
idx = np.argmax(scores)
idx, scores[idx]

(np.int64(0), np.float32(0.4874058))

In [40]:
documents[idx]

{'id': '9e508f2212',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: When does the course start?',
 'answer': "A new cohort runs roughly January–April every year. For the current cohort's exact start date and registration link, check the [course repo README](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n\n- Register via the link in the course repo before the cohort starts.\n- Join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.\n- Join DataTalks.Club's [Slack](https://datatalks.club/docs/general/slack/) and the `#course-data-engineering` channel."}

In [41]:
top5 = np.argsort(scores)[-5:]

In [42]:
top5 = top5[::-1]
top5

array([0])

In [45]:
for idx in top5:
    print(scores[idx])
    print(documents[idx])
    print()

0.4874058
{'id': '9e508f2212', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: When does the course start?', 'answer': "A new cohort runs roughly January–April every year. For the current cohort's exact start date and registration link, check the [course repo README](https://github.com/DataTalksClub/data-engineering-zoomcamp).\n\n- Register via the link in the course repo before the cohort starts.\n- Join the [course Telegram channel](https://t.me/dezoomcamp) for announcements.\n- Join DataTalks.Club's [Slack](https://datatalks.club/docs/general/slack/) and the `#course-data-engineering` channel."}



In [18]:
from ingest import load_faq_data

documents = load_faq_data()

In [19]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

In [20]:
from tqdm.auto import tqdm

In [21]:
batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [22]:
import numpy as np
X = np.array(vectors)

In [23]:
X.shape

(1350, 384)

In [24]:
query = "Can I still join the course after the start date?"
v_query = model.encode(query)

In [25]:
scores = X.dot(v_query)

In [26]:
scores = [v_query.dot(X[i]) for i in range(len(X))]

In [27]:
idx = np.argmax(scores)
idx, scores[idx]

(np.int64(2), np.float32(0.76294106))

In [28]:
documents[idx]

{'id': '3f1424af17',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

In [29]:
top5 = np.argsort(scores)[-5:]

In [31]:
for idx in top5:
    print(scores[idx])
    print(documents[idx])
    print()

0.56009996
{'id': '068529125b', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I follow the course after it finishes?', 'answer': 'Yes, we will keep all the materials available, so you can follow the course at your own pace after it finishes.\n\nYou can also continue reviewing the homeworks and prepare for the next cohort. You can also start working on your final capstone project.'}

0.6536312
{'id': '74eb249bbf', 'course': 'llm-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'I just discovered the course. Can I still join?', 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}

0.7192131
{'id': '41aabbd7c5', 'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'The course has already started. Can I still join it?', 'answer': 'Yes, you can. Even though you missed the start date

In [32]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=["course"])
vindex.fit(X, documents)

In [33]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vindex.search(query_vector, num_results=5)

In [34]:
results[0]

{'id': '74eb249bbf',
 'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}

In [35]:
results = vindex.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [36]:
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [37]:
from ingest import load_faq_data, build_index

documents = load_faq_data()
index = build_index(documents)

In [38]:
from rag_helper import RAGBase

assistant = RAGBase(
    index=index,
    llm_client=openai_client,
)

In [39]:
query = "I just found out about the program, can I still sign up?"
assistant.rag(query)

'Yes, but if you want to receive a certificate, you need to submit your project while the course is still accepting submissions.'

In [40]:

class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {"course": self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

In [41]:
vector_assistant = RAGVector(
    embedder=model,
    index=vindex,
    llm_client=openai_client,
)

In [42]:
vector_assistant.rag("the program has already begun, can I still sign up?")

'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'

In [43]:
from sqlitesearch import VectorSearchIndex

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

In [44]:
vs_index.fit(vectors, documents)

In [45]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vs_index.search(query_vector, num_results=5)

In [46]:
results

[{'id': '74eb249bbf',
  'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'I just discovered the course. Can I still join?',
  'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'},
 {'id': '41aabbd7c5',
  'course': 'machine-learning-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'The course has already started. Can I still join it?',
  'answer': 'Yes, you can. Even though you missed the start date, you can register for the course. You won’t be able to submit some of the homeworks, but you can still take part in the course.\n\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'},
 {'id': '2d8b16c2a0',
  'course': 'mlops-zoomcamp',
  'section':

In [47]:
results = vs_index.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [48]:
vs_index.close()

In [49]:
from sentence_transformers import SentenceTransformer
from sqlitesearch import VectorSearchIndex

model = SentenceTransformer("all-MiniLM-L6-v2")

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [51]:
query_vector = model.encode("How do I run Kafka?")
results = vs_index.search(query_vector, num_results=5)

In [53]:
from rag_helper import RAGBase
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {"course": self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

vector_assistant = RAGVector(
    embedder=model,
    index=vs_index,
    llm_client=openai_client,
)

In [54]:
vector_assistant.rag("the program has already begun, can I still sign up?")

'Yes, you can still join. You can start learning and submitting homework even after the course has begun, as long as the submission form is still open. If you want a certificate, you’ll need to submit your project while submissions are still being accepted.'

In [55]:
vs_index.close()

In [1]:
from tqdm.auto import tqdm

from ingest import load_faq_data
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

documents = load_faq_data()
texts = [doc["question"] + " " + doc["answer"] for doc in documents]

batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

In [2]:
import psycopg

conn = psycopg.connect(
    "postgresql://user:pswd@localhost:5432/faq"
)
conn.execute("CREATE EXTENSION IF NOT EXISTS vector")

<psycopg.Cursor [COMMAND_OK] [INTRANS] (host=localhost user=user database=faq) at 0x79cc51e1aa50>

In [ ]:
import psycopg

conn = psycopg.connect(
    "postgresql://user:pswd@localhost:5432/faq"
)
conn.execute("CREATE EXTENSION IF NOT EXISTS vector")